---
title: "Homework 5"
author: "Eva Juengling Bean and Elijah Khan"
format: html
editor: visual
---

```{r}
#| label: load libraries
#| echo: true
#| warning: false

library(usethis)
library(tidyverse)
library(here)
library(janitor)
library(dataRetrieval)
```

```{r}
#|label: download data
#| echo: true

siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010"  # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"

temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate)

# rename columns for clarity
colnames(temp_data) <- c("agency_cd", "site_no", "Date", "temp_C")
# extract some date info for use later
temp_data$month = month(temp_data$Date, label=TRUE)
temp_data$year = year(temp_data$Date)

write.csv(temp_data, here("hw.week.5", "temp.data.csv"))

temp.data <- read.csv(here("hw.week.5", "temp.data.csv"))

# check by plotting
ggplot(temp.data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_bw()
```
